### ISSUE TITLE
Outreach to original author

### ISSUE THREAD

**Issue by jcbhmr** [devcontainers-community/features-tinygo#1]
Hello @lee-orr! 👋

I noticed that in your https://github.com/lee-orr/rusty-dev-containers collection _most_ of it is Rust-specific but there was one part that jumped out to me as a nice fit for a more generic umbrella: tinygo.

I figured you might be interested in this project 😊

**Comment by lee-orr** [comment]
I think this is great! I added that one due to a very specific situation, and think having a more dedicated tiny go one works better. Thanks for pinging me on this!

**Comment by lee-orr** [comment]
@jcbhmr - Is it OK with you if I deprecate my version of the feature and recommend people go to yours instead?

**Comment by jcbhmr** [comment]
Sounds good! 👍

**Comment by jcbhmr** [comment]
it looks like you're involved with other devcontainer stuffs! cool! if you ever have an itch to make more features or templates or anything whathaveyou, ive invited you to the @devcontainers-community org. you **dont have to accept** if you dont want ❤️
